Update min PHP testing version from PHP 7.4 to 8.1 (#35964)
- PHP 7.4 and 8.0 have been EOL https://www.php.net/supported-versions.php
- See go/drop-php-8.0 for more details

Most of the changes came from `generate_projects.sh` after updating the `tools/buildgen/plugins/expand_version.py` file. The change to `tools/internal_ci/helper_scripts/prepare_build_macos_rc` is manual.

Closes #35964

COPYBARA_INTEGRATE_REVIEW=https://github.com/grpc/grpc/pull/35964 from stanley-cheung:php-update-to-8_1 0c24c4eac21acae9208473363b1d3f737976ccd3
PiperOrigin-RevId: 609495798

diff --git a/tools/internal_ci/helper_scripts/prepare_build_macos_rc b/tools/internal_ci/helper_scripts/prepare_build_macos_rc
--- a/tools/internal_ci/helper_scripts/prepare_build_macos_rc
+++ b/tools/internal_ci/helper_scripts/prepare_build_macos_rc
@@ -196,19 +196,22 @@ fi
 
 if [ "${PREPARE_BUILD_INSTALL_DEPS_PHP}" == "true" ]
 then
-  # php7.4 should already be installed on kokoro monterey image, so this should be instantaneous.
-  time brew install php@7.4 || true
-  export LDFLAGS="-L/usr/local/opt/php@7.4/lib ${LDFLAGS}"
-  export CPPFLAGS="-I/usr/local/opt/php@7.4/include ${CPPFLAGS}"
-  export PATH="/usr/local/opt/php@7.4/bin:/usr/local/opt/php@7.4/sbin:${PATH}"
+  time brew install php@8.1 || true
+  export LDFLAGS="-L/usr/local/opt/php@8.1/lib ${LDFLAGS}"
+  export CPPFLAGS="-I/usr/local/opt/php@8.1/include ${CPPFLAGS}"
+  export PATH="/usr/local/opt/php@8.1/bin:/usr/local/opt/php@8.1/sbin:${PATH}"
 
-  # the exit code from "brew install php@7.4" is useless
+  # the exit code from "brew install php@8.1" is useless
   # so instead we check if PHP was indeed installed successfully.
   # Failing early is better than cryptic errors later in the build process.
-  /usr/local/opt/php@7.4/bin/php --version
+  /usr/local/opt/php@8.1/bin/php --version
 
   # Workaround for https://github.com/Homebrew/homebrew-core/issues/41081
   mkdir -p /usr/local/lib/php/pecl
+
+  # Download the right version of phpunit to match PHP version
+  sudo curl -sSL https://phar.phpunit.de/phpunit-9.5.9.phar -o /usr/local/bin/phpunit
+  sudo chmod +x /usr/local/bin/phpunit
 fi
 
 # TODO(jtattermusch): better debugging of clock skew, remove once not needed
