feat: introduce a retry wrapper for apt-get installations in Dockerfiles to improve reliability - all in one

diff --git a/src/python/grpcio_tests/tests_py3_only/interop/Dockerfile.client b/src/python/grpcio_tests/tests_py3_only/interop/Dockerfile.client
--- a/src/python/grpcio_tests/tests_py3_only/interop/Dockerfile.client
+++ b/src/python/grpcio_tests/tests_py3_only/interop/Dockerfile.client
@@ -1,6 +1,67 @@
 FROM python:3.10-slim-bookworm
 
-RUN apt-get update -y && apt-get upgrade -y && apt-get install -y build-essential clang curl
+#=================
+# Install apt-get-install-retry wrapper script
+#=================
+#  Create wrapper for apt-get
+
+COPY --chmod=+x <<-"EOF" /usr/local/bin/apt-get-install-retry
+#!/usr/bin/env bash
+# Copyright 2026 The gRPC Authors
+#
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
+#
+#     http://www.apache.org/licenses/LICENSE-2.0
+#
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+
+
+# Ensure all tracking are registered
+
+PS4="+ \$(date +[%H:%M:%S_%Z]) "
+set -xeuo pipefail
+
+# Ensure package to install is provided
+if [ $# -eq 0 ]; then
+  echo "Error: No package name provided to install with apt-get." >&2
+  exit 1
+fi
+
+PACKAGES=("$@")
+
+MAX_RETRIES=4
+# Initial delay, will grow exponentially
+delay=3
+
+echo "Installing packages ${PACKAGES} using apt-get"
+
+for i in $(seq 1 $MAX_RETRIES); do
+  echo "Running apt-get update and install (attempt ${i})..."
+  if apt-get update && apt-get install -y "${PACKAGES[@]}"; then
+    echo "apt-get succeeded on attempt ${i}.";
+    break;
+  else
+    if [ "${i}" -eq "${MAX_RETRIES}" ]; then
+      echo "Max retries reached (${MAX_RETRIES}). apt-get failed permanently." >&2
+      exit 1;
+    fi
+    
+    echo "apt-get failed on attempt ${i}. Waiting $(($delay**$i)) seconds before retrying..."
+    sleep $(($delay**$i));
+  fi
+done
+
+EOF
+
+
+RUN apt-get update -y && apt-get upgrade -y
+RUN apt-get-install-retry build-essential clang curl
 
 WORKDIR /workdir
 
@@ -27,12 +88,13 @@ ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
 RUN chmod +x /tini
 
 FROM python:3.10-slim-bookworm
+COPY --from=0 /usr/local/bin/apt-get-install-retry /usr/local/bin/apt-get-install-retry
+
 
 ENV GRPC_VERBOSITY="DEBUG"
 ENV GRPC_TRACE="xds_client,xds_resolver,xds_cluster_manager_lb,cds_lb,xds_cluster_resolver_lb,priority_lb,xds_cluster_impl_lb,weighted_target_lb,ring_hash_lb,outlier_detection_lb"
 
-RUN apt-get update -y \
-  && apt-get install -y python3 \
+RUN apt-get-install-retry python3 \
   && apt-get -y autoremove \
   && rm -rf /var/lib/apt/lists/*
 
diff --git a/tools/dockerfile/distribtest/csharp_debian11_x64/Dockerfile b/tools/dockerfile/distribtest/csharp_debian11_x64/Dockerfile
--- a/tools/dockerfile/distribtest/csharp_debian11_x64/Dockerfile
+++ b/tools/dockerfile/distribtest/csharp_debian11_x64/Dockerfile
@@ -13,21 +13,80 @@
 # limitations under the License.
 
 FROM debian:11
+#=================
+# Install apt-get-install-retry wrapper script
+#=================
+#  Create wrapper for apt-get
+
+COPY --chmod=+x <<-"EOF" /usr/local/bin/apt-get-install-retry
+#!/usr/bin/env bash
+# Copyright 2026 The gRPC Authors
+#
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
+#
+#     http://www.apache.org/licenses/LICENSE-2.0
+#
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+
+
+# Ensure all tracking are registered
+
+PS4="+ \$(date +[%H:%M:%S_%Z]) "
+set -xeuo pipefail
+
+# Ensure package to install is provided
+if [ $# -eq 0 ]; then
+  echo "Error: No package name provided to install with apt-get." >&2
+  exit 1
+fi
+
+PACKAGES=("$@")
+
+MAX_RETRIES=4
+# Initial delay, will grow exponentially
+delay=3
+
+echo "Installing packages ${PACKAGES} using apt-get"
+
+for i in $(seq 1 $MAX_RETRIES); do
+  echo "Running apt-get update and install (attempt ${i})..."
+  if apt-get update && apt-get install -y "${PACKAGES[@]}"; then
+    echo "apt-get succeeded on attempt ${i}.";
+    break;
+  else
+    if [ "${i}" -eq "${MAX_RETRIES}" ]; then
+      echo "Max retries reached (${MAX_RETRIES}). apt-get failed permanently." >&2
+      exit 1;
+    fi
+    
+    echo "apt-get failed on attempt ${i}. Waiting $(($delay**$i)) seconds before retrying..."
+    sleep $(($delay**$i));
+  fi
+done
+
+EOF
+
+
 
 RUN apt update && apt -y upgrade
-RUN apt install -y apt-transport-https ca-certificates curl dirmngr gnupg unzip wget && apt clean
+RUN apt-get-install-retry apt-transport-https ca-certificates curl dirmngr gnupg unzip wget && apt clean
 
 # Install mono
 RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF \
     && echo "deb https://download.mono-project.com/repo/debian stable-buster main" | tee /etc/apt/sources.list.d/mono-official-stable.list \
-    && apt update && apt install -y mono-devel nuget \
+    && apt-get-install-retry mono-devel nuget \
     && apt clean
 
 # Install dotnet SDK
 RUN wget https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb \
     && dpkg -i packages-microsoft-prod.deb \
-    && apt update \
-    && apt install -y dotnet-sdk-3.1 \
+    && apt-get-install-retry dotnet-sdk-3.1 \
     && apt clean
 
 # Make sure the mono certificate store is up-to-date to prevent issues with nuget restore
