feat: introduce a retry wrapper for apt-get installations in Dockerfiles to improve reliability

diff --git a/tools/dockerfile/test/sanity/Dockerfile b/tools/dockerfile/test/sanity/Dockerfile
--- a/tools/dockerfile/test/sanity/Dockerfile
+++ b/tools/dockerfile/test/sanity/Dockerfile
@@ -15,55 +15,64 @@
 FROM silkeh/clang:19-bookworm
 
 #=================
-# Basic C core dependencies
+#  Create wrapper for apt-get
 
-# C/C++ dependencies according to https://github.com/grpc/grpc/blob/master/BUILDING.md
-RUN apt-get update && apt-get install -y \
-  build-essential \
-  autoconf \
-  libtool \
-  pkg-config \
-  && apt-get clean
-
-# GCC
-RUN apt-get update && apt-get install -y \
-  gcc \
-  g++ \
-  && apt-get clean
-
-# libc6
-RUN apt-get update && apt-get install -y \
-  libc6 \
-  libc6-dbg \
-  libc6-dev \
-  && apt-get clean
-
-# Tools
-RUN apt-get update && apt-get install -y \
-  bzip2 \
-  curl \
-  dnsutils \
-  git \
-  lcov \
-  make \
-  strace \
-  time \
-  unzip \
-  wget \
-  zip \
-  && apt-get clean
-
-#=================
-# Setup git to access working directory across docker boundary.
-# This avoids the "fatal: detected dubious ownership in repository XYZ"
-# git error.
-
-RUN git config --global --add safe.directory '*'
-RUN git config --global protocol.file.allow always
+COPY --chmod=+x <<-"EOF" /usr/local/bin/apt-get-install-retry
+#!/usr/bin/env bash
+# Copyright 2026 The gRPC Authors
+#
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
+#
+#     http://www.apache.org/licenses/LICENSE-2.0
+#
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
 
 
+# Ensure all tracking are registered
 
-RUN apt update && apt install -y python3 python3-pip && apt clean
+PS4="+ \$(date +[%H:%M:%S_%Z]) "
+set -xeuo pipefail
+
+# Ensure package to install is provided
+if [ $# -eq 0 ]; then
+  echo "Error: No package name provided to install with apt-get." >&2
+  exit 1
+fi
+
+PACKAGES=("$@")
+
+MAX_RETRIES=4
+# Initial delay, will grow exponentially
+delay=3
+
+echo "Installing packages ${PACKAGES} using apt-get"
+
+for i in $(seq 1 $MAX_RETRIES); do
+  echo "Running apt-get update and install (attempt ${i})..."
+  if apt-get update && apt-get install -y "${PACKAGES[@]}"; then
+    echo "apt-get succeeded on attempt ${i}.";
+    break;
+  else
+    if [ "${i}" -eq "${MAX_RETRIES}" ]; then
+      echo "Max retries reached (${MAX_RETRIES}). apt-get failed permanently." >&2
+      exit 1;
+    fi
+    
+    echo "apt-get failed on attempt ${i}. Waiting $(($delay**$i)) seconds before retrying..."
+    sleep $(($delay**$i));
+  fi
+done
+
+EOF
+
+
+RUN /usr/local/bin/apt-get-install-retry python3 python3-pip && apt clean
 
 RUN python3 -m pip install --break-system-packages --upgrade google-auth==1.23.0 google-api-python-client==1.12.8 oauth2client==4.1.0
 
@@ -77,7 +86,7 @@ RUN mkdir /var/local/jenkins
 # autoconf automake libtool curl shellcheck: main dependencies
 # jq git: prerequisites for the clang-tidy script
 # libgtest-dev: otherwise clang-tidy will report missing <gtest/gtest.h> header
-RUN apt install -y \
+RUN /usr/local/bin/apt-get-install-retry \
     autoconf \
     automake \
     curl \
