updated with DEBIAN_FRONTEND=noninteractive

diff --git a/tools/dockerfile/test/sanity/Dockerfile b/tools/dockerfile/test/sanity/Dockerfile
--- a/tools/dockerfile/test/sanity/Dockerfile
+++ b/tools/dockerfile/test/sanity/Dockerfile
@@ -14,9 +14,6 @@
 
 FROM silkeh/clang:19-bookworm
 
-#=================
-#  Create wrapper for apt-get
-
 RUN echo '#!/usr/bin/env bash' > /usr/local/bin/apt-get-install-retry && \
     echo '# Copyright 2026 The gRPC Authors' >> /usr/local/bin/apt-get-install-retry && \
     echo '#' >> /usr/local/bin/apt-get-install-retry && \
@@ -31,43 +28,49 @@ RUN echo '#!/usr/bin/env bash' > /usr/local/bin/apt-get-install-retry && \
     echo '# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.' >> /usr/local/bin/apt-get-install-retry && \
     echo '# See the License for the specific language governing permissions and' >> /usr/local/bin/apt-get-install-retry && \
     echo '# limitations under the License.' >> /usr/local/bin/apt-get-install-retry && \
-        echo '' >> /usr/local/bin/apt-get-install-retry && \
-        echo '' >> /usr/local/bin/apt-get-install-retry && \
-        echo '# Ensure all tracking is registered' >> /usr/local/bin/apt-get-install-retry && \
-        echo '' >> /usr/local/bin/apt-get-install-retry && \
-        echo 'PS4="+ \$(date +[%H:%M:%S_%Z]) "' >> /usr/local/bin/apt-get-install-retry && \
-        echo 'set -xeuo pipefail' >> /usr/local/bin/apt-get-install-retry && \
-        echo '' >> /usr/local/bin/apt-get-install-retry && \
-        echo '# Ensure package to install is provided' >> /usr/local/bin/apt-get-install-retry && \
-        echo 'if [ $# -eq 0 ]; then' >> /usr/local/bin/apt-get-install-retry && \
-        echo '  echo "Error: No package name provided to install with apt-get." >&2' >> /usr/local/bin/apt-get-install-retry && \
-        echo '  exit 1' >> /usr/local/bin/apt-get-install-retry && \
-        echo 'fi' >> /usr/local/bin/apt-get-install-retry && \
-        echo '' >> /usr/local/bin/apt-get-install-retry && \
-        echo 'PACKAGES=("$@")' >> /usr/local/bin/apt-get-install-retry && \
-        echo '' >> /usr/local/bin/apt-get-install-retry && \
-        echo 'MAX_RETRIES=4' >> /usr/local/bin/apt-get-install-retry && \
-        echo '# Initial delay, will grow exponentially' >> /usr/local/bin/apt-get-install-retry && \
-        echo 'delay=3' >> /usr/local/bin/apt-get-install-retry && \
-        echo '' >> /usr/local/bin/apt-get-install-retry && \
-        echo 'echo "Installing packages ${PACKAGES[*]} using apt-get"' >> /usr/local/bin/apt-get-install-retry && \
-        echo '' >> /usr/local/bin/apt-get-install-retry && \
-        echo 'for i in $(seq 1 $MAX_RETRIES); do' >> /usr/local/bin/apt-get-install-retry && \
-        echo '  echo "Running apt-get update and install (attempt ${i})..."' >> /usr/local/bin/apt-get-install-retry && \
-        echo '    if apt-get update && apt-get install -y "${PACKAGES[@]}"; then' >> /usr/local/bin/apt-get-install-retry && \
-        echo '    echo "apt-get succeeded on attempt ${i}.";' >> /usr/local/bin/apt-get-install-retry && \
-        echo '    break;' >> /usr/local/bin/apt-get-install-retry && \
-        echo '  else' >> /usr/local/bin/apt-get-install-retry && \
-        echo '    if [ "${i}" -eq "${MAX_RETRIES}" ]; then' >> /usr/local/bin/apt-get-install-retry && \
-        echo '      echo "Max retries reached (${MAX_RETRIES}). apt-get failed permanently." >&2' >> /usr/local/bin/apt-get-install-retry && \
-        echo '      exit 1;' >> /usr/local/bin/apt-get-install-retry && \
-        echo '    fi' >> /usr/local/bin/apt-get-install-retry && \
-        echo '    ' >> /usr/local/bin/apt-get-install-retry && \
-        echo '    echo "apt-get failed on attempt ${i}. Waiting $((delay**i)) seconds before retrying..."' >> /usr/local/bin/apt-get-install-retry && \
-        echo '    sleep $((delay**i));' >> /usr/local/bin/apt-get-install-retry && \
-        echo '  fi' >> /usr/local/bin/apt-get-install-retry && \
-        echo 'done' >> /usr/local/bin/apt-get-install-retry && \
-        chmod +x /usr/local/bin/apt-get-install-retry
+    echo '' >> /usr/local/bin/apt-get-install-retry && \
+    echo '' >> /usr/local/bin/apt-get-install-retry && \
+    echo '# Ensure all tracking is registered' >> /usr/local/bin/apt-get-install-retry && \
+    echo '' >> /usr/local/bin/apt-get-install-retry && \
+    echo 'PS4="+ \$(date +[%H:%M:%S_%Z]) "' >> /usr/local/bin/apt-get-install-retry && \
+    echo 'set -xeuo pipefail' >> /usr/local/bin/apt-get-install-retry && \
+    echo '' >> /usr/local/bin/apt-get-install-retry && \
+    echo '# Ensure package to install is provided' >> /usr/local/bin/apt-get-install-retry && \
+    echo 'if [ $# -eq 0 ]; then' >> /usr/local/bin/apt-get-install-retry && \
+    echo '  echo "Error: No package name provided to install with apt-get." >&2' >> /usr/local/bin/apt-get-install-retry && \
+    echo '  exit 1' >> /usr/local/bin/apt-get-install-retry && \
+    echo 'fi' >> /usr/local/bin/apt-get-install-retry && \
+    echo '' >> /usr/local/bin/apt-get-install-retry && \
+    echo 'PACKAGES=("$@")' >> /usr/local/bin/apt-get-install-retry && \
+    echo '' >> /usr/local/bin/apt-get-install-retry && \
+    echo 'MAX_RETRIES=4' >> /usr/local/bin/apt-get-install-retry && \
+    echo '# Initial delay, will grow exponentially' >> /usr/local/bin/apt-get-install-retry && \
+    echo 'delay=3' >> /usr/local/bin/apt-get-install-retry && \
+    echo '' >> /usr/local/bin/apt-get-install-retry && \
+    echo 'echo "Installing packages ${PACKAGES[*]} using apt-get"' >> /usr/local/bin/apt-get-install-retry && \
+    echo '' >> /usr/local/bin/apt-get-install-retry && \
+    echo 'for i in $(seq 1 $MAX_RETRIES); do' >> /usr/local/bin/apt-get-install-retry && \
+    echo '  echo "Running apt-get update and install (attempt ${i})..."' >> /usr/local/bin/apt-get-install-retry && \
+    echo '  if DEBIAN_FRONTEND=noninteractive apt-get update -qq && \' >> /usr/local/bin/apt-get-install-retry && \
+    echo '     DEBIAN_FRONTEND=noninteractive apt-get install -qq -y \' >> /usr/local/bin/apt-get-install-retry && \
+    echo '     -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" \' >> /usr/local/bin/apt-get-install-retry && \
+    echo '      "${PACKAGES[@]}"; then' >> /usr/local/bin/apt-get-install-retry && \
+    echo '    echo "apt-get succeeded on attempt ${i}.";' >> /usr/local/bin/apt-get-install-retry && \
+    echo '    break;' >> /usr/local/bin/apt-get-install-retry && \
+    echo '  else' >> /usr/local/bin/apt-get-install-retry && \
+    echo '    if [ "${i}" -eq "${MAX_RETRIES}" ]; then' >> /usr/local/bin/apt-get-install-retry && \
+    echo '      echo "Max retries reached (${MAX_RETRIES}). apt-get failed permanently." >&2' >> /usr/local/bin/apt-get-install-retry && \
+    echo '      exit 1;' >> /usr/local/bin/apt-get-install-retry && \
+    echo '    fi' >> /usr/local/bin/apt-get-install-retry && \
+    echo '    ' >> /usr/local/bin/apt-get-install-retry && \
+    echo '    echo "apt-get failed on attempt ${i}. Waiting $((delay**i)) seconds before retrying..."' >> /usr/local/bin/apt-get-install-retry && \
+    echo '    sleep $((delay**i));' >> /usr/local/bin/apt-get-install-retry && \
+    echo '  fi' >> /usr/local/bin/apt-get-install-retry && \
+    echo 'done' >> /usr/local/bin/apt-get-install-retry && \
+    chmod +x /usr/local/bin/apt-get-install-retry
+
+
+
 
 
 RUN apt-get-install-retry python3 python3-pip
