feat: introduce a retry wrapper for apt-get installations in Dockerfiles to improve reliability + pr cleanup

diff --git a/tools/dockerfile/interoptest/grpc_interop_go1.19/Dockerfile b/tools/dockerfile/interoptest/grpc_interop_go1.19/Dockerfile
--- a/tools/dockerfile/interoptest/grpc_interop_go1.19/Dockerfile
+++ b/tools/dockerfile/interoptest/grpc_interop_go1.19/Dockerfile
@@ -14,6 +14,65 @@
 
 FROM golang:1.19
 
+# Install apt-get-install-retry wrapper script
+#=================
+#  Create wrapper for apt-get
+
+COPY --chmod=+x <<-"EOF" /usr/local/bin/apt-get-install-retry
+#!/usr/bin/env bash
+# Copyright 2026 The gRPC Authors
+#
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
+#
+#     http://www.apache.org/licenses/LICENSE-2.0
+#
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+
+
+# Ensure all tracking are registered
+
+PS4="+ \$(date +[%H:%M:%S_%Z]) "
+set -xeuo pipefail
+
+# Ensure package to install is provided
+if [ $# -eq 0 ]; then
+  echo "Error: No package name provided to install with apt-get." >&2
+  exit 1
+fi
+
+PACKAGES=("$@")
+
+MAX_RETRIES=4
+# Initial delay, will grow exponentially
+delay=3
+
+echo "Installing packages ${PACKAGES} using apt-get"
+
+for i in $(seq 1 $MAX_RETRIES); do
+  echo "Running apt-get update and install (attempt ${i})..."
+  if apt-get update && apt-get install -y "${PACKAGES[@]}"; then
+    echo "apt-get succeeded on attempt ${i}.";
+    break;
+  else
+    if [ "${i}" -eq "${MAX_RETRIES}" ]; then
+      echo "Max retries reached (${MAX_RETRIES}). apt-get failed permanently." >&2
+      exit 1;
+    fi
+    
+    echo "apt-get failed on attempt ${i}. Waiting $(($delay**$i)) seconds before retrying..."
+    sleep $(($delay**$i));
+  fi
+done
+
+EOF
+
+
 # Using login shell removes Go from path, so we add it.
 RUN ln -s /usr/local/go/bin/go /usr/local/bin
 
@@ -31,12 +90,12 @@ RUN git config --global protocol.file.allow always
 # Basic python dependencies to be able to run tools/run_tests python scripts
 # These dependencies are not sufficient to build gRPC Python, gRPC Python
 # deps are defined elsewhere (e.g. python_deps.include)
-RUN apt-get update && apt-get install -y \
+RUN /usr/local/bin/apt-get-install-retry \
   python3 \
   python3-pip \
   python3-setuptools \
-  python3-yaml \
-  && apt-get clean
+  python3-yaml
+ 
 
 # use pinned version of pip to avoid sudden breakages
 # Some newer distros that have already implemented PEP 668. Use of
diff --git a/tools/dockerfile/test/python_debian11_default_arm64/Dockerfile b/tools/dockerfile/test/python_debian11_default_arm64/Dockerfile
--- a/tools/dockerfile/test/python_debian11_default_arm64/Dockerfile
+++ b/tools/dockerfile/test/python_debian11_default_arm64/Dockerfile
@@ -12,13 +12,72 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-FROM arm64v8/debian:11
+FROM --platform=linux/arm64/v8 arm64v8/debian:11
 
 #=================
+# Install apt-get-install-retry wrapper script
+#=================
+#  Create wrapper for apt-get
+
+COPY --chmod=+x <<-"EOF" /usr/local/bin/apt-get-install-retry
+#!/usr/bin/env bash
+# Copyright 2026 The gRPC Authors
+#
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
+#
+#     http://www.apache.org/licenses/LICENSE-2.0
+#
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+
+
+# Ensure all tracking are registered
+
+PS4="+ \$(date +[%H:%M:%S_%Z]) "
+set -xeuo pipefail
+
+# Ensure package to install is provided
+if [ $# -eq 0 ]; then
+  echo "Error: No package name provided to install with apt-get." >&2
+  exit 1
+fi
+
+PACKAGES=("$@")
+
+MAX_RETRIES=4
+# Initial delay, will grow exponentially
+delay=3
+
+echo "Installing packages ${PACKAGES} using apt-get"
+
+for i in $(seq 1 $MAX_RETRIES); do
+  echo "Running apt-get update and install (attempt ${i})..."
+  if apt-get update && apt-get install -y "${PACKAGES[@]}"; then
+    echo "apt-get succeeded on attempt ${i}.";
+    break;
+  else
+    if [ "${i}" -eq "${MAX_RETRIES}" ]; then
+      echo "Max retries reached (${MAX_RETRIES}). apt-get failed permanently." >&2
+      exit 1;
+    fi
+    
+    echo "apt-get failed on attempt ${i}. Waiting $(($delay**$i)) seconds before retrying..."
+    sleep $(($delay**$i));
+  fi
+done
+
+EOF
+
+
 # Basic C core dependencies
 
 # C/C++ dependencies according to https://github.com/grpc/grpc/blob/master/BUILDING.md
-RUN apt-get update && apt-get install -y \
+RUN /usr/local/bin/apt-get-install-retry \
   build-essential \
   autoconf \
   libtool \
@@ -26,20 +85,20 @@ RUN apt-get update && apt-get install -y \
   && apt-get clean
 
 # GCC
-RUN apt-get update && apt-get install -y \
+RUN /usr/local/bin/apt-get-install-retry \
   gcc \
   g++ \
   && apt-get clean
 
 # libc6
-RUN apt-get update && apt-get install -y \
+RUN /usr/local/bin/apt-get-install-retry \
   libc6 \
   libc6-dbg \
   libc6-dev \
   && apt-get clean
 
 # Tools
-RUN apt-get update && apt-get install -y \
+RUN /usr/local/bin/apt-get-install-retry \
   bzip2 \
   curl \
   dnsutils \
@@ -68,13 +127,13 @@ RUN mkdir /var/local/jenkins
 
 # Python test coverage requires libsqlite3, and it have
 # to be installed before Python.
-RUN apt-get update && apt-get install -y libsqlite3-dev
+RUN /usr/local/bin/apt-get-install-retry libsqlite3-dev
 
 #=================
 # Compile CPython 3.10.3 from source
 
-RUN apt-get update && apt-get install -y zlib1g-dev libssl-dev libsqlite3-dev && apt-get clean
-RUN apt-get update && apt-get install -y jq build-essential libffi-dev && apt-get clean
+RUN /usr/local/bin/apt-get-install-retry zlib1g-dev libssl-dev libsqlite3-dev
+RUN /usr/local/bin/apt-get-install-retry jq build-essential libffi-dev
 
 RUN cd /tmp && \
     wget -q https://www.python.org/ftp/python/3.10.3/Python-3.10.3.tgz && \
@@ -99,7 +158,7 @@ RUN python3.10 -m pip install --upgrade google-auth==1.23.0 google-api-python-cl
 # Install cmake
 # Note that this step should be only used for distributions that have new enough cmake to satisfy gRPC's cmake version requirement.
 
-RUN apt-get update && apt-get install -y cmake && apt-get clean
+RUN /usr/local/bin/apt-get-install-retry cmake
 
 #=================
 # Install ccache
